const collar = [
  'function sx() external view returns (uint256)',
  'function sy() external view returns (uint256)',
  'function sk() external view returns (uint256)',
  'function swap_sqp() external view returns (uint256)',
  'function calc_k(uint256,uint256) external view returns (uint256)',
  'function get_dx(uint256) external view returns (uint256)',
  'function get_dy(uint256) external view returns (uint256)',
  'function get_dk(uint256, uint256) external view returns (uint256)',
  'function earned(address) external view returns (uint256)',
  'function get_dxdy(uint256) external view returns (uint256, uint256)',
  'function borrow_want(uint256, uint256) external',
  'function burn_call(uint256) external',
  'function burn_dual(uint256) external',
  'function repay_both(uint256, uint256) external',
  'function mint(uint256, uint256, uint256) external',
  'function withdraw_both(uint256) external',
  'function swap_coll_to_min_want(uint256, uint256) external',
  'function swap_want_to_min_coll(uint256, uint256) external',
  'function claim_reward() external',
  'function swap_fee() public pure returns (uint256)',
  'function burn_and_claim(uint256) public',
  'function mint_dual(uint256) public',
]

export default collar
